; InputAutoCfg.ini for Mupen64Plus SDL Input plugin

; Keyboard_START
[Keyboard]
plugged = True
plugin = 2
mouse = False
DPad R = key(100)
DPad L = key(97)
DPad D = key(115)
DPad U = key(119)
Start = key(13)
Z Trig = key(122)
B Button = key(306)
A Button = key(304)
C Button R = key(108)
C Button L = key(106)
C Button D = key(107)
C Button U = key(105)
R Trig = key(99)
L Trig = key(120)
Mempak switch = key(44)
Rumblepak switch = key(46)
X Axis = key(276,275)
Y Axis = key(273,274)
; Keyboard_END


; Xbox Series X Controller_START 
[Xbox Series X Controller]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
Mempak switch = button() 
Rumblepak switch = button() 
DPad U = hat(0 Up) 
DPad D = hat(0 Down) 
DPad L = hat(0 Left) 
DPad R = hat(0 Right)
C Button U = axis(5+) 
C Button D = button(1) 
C Button L = 
C Button R = button(4)
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)  
L Trig = axis(4+)
R Trig = button(7) 
A Button = button(0)
B Button = button(3)
Z Trig = button(6)  
Start = button(11) 
; Xbox Series X Controller_END 

; Xbox 360 Controller_START 
[Xbox 360 Controller]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
Mempak switch = button(9) 
Rumblepak switch = button(10) 
DPad U = hat(0 Up)  
DPad D = hat(0 Down)  
DPad L = hat(0 Left)  
DPad R = hat(0 Right)  
C Button U = axis(2+)   
C Button D = button(1)
C Button L =  
C Button R = button(3) 
X Axis = axis(0-,0+)  
Y Axis = axis(1-,1+)  
L Trig = axis(2+) 
R Trig = button(5)  
A Button = button(0)  
B Button = button(2)  
Z Trig = button(4) 
Start = button(7)  
; Xbox 360 Controller_END 

; ShanWan PC/PS3/Android_START 
[ShanWan PC/PS3/Android]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
Mempak switch = button(10) 
Rumblepak switch = button(11) 
DPad U = hat(0 Up)  
DPad D = hat(0 Down)  
DPad L = hat(0 Left)  
DPad R = hat(0 Right)  
C Button U = button(6) 
C Button D = button(1) 
C Button L = 
C Button R = button(0)  
X Axis = axis(0-,0+)  
Y Axis = axis(1-,1+)  
L Trig = button(6)  
R Trig = button(5)  
A Button = button(2)  
B Button = button(3)  
Z Trig = button(4)  
Start = button(9)  
; ShanWan PC/PS3/Android_END 

; Twin USB Joystick_START 
[Twin USB Joystick]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
Mempak switch = button(10) 
Rumblepak switch = button(11) 
DPad U = hat(0 Up)  
DPad D = hat(0 Down)  
DPad L = hat(0 Left)  
DPad R = hat(0 Right)  
C Button U = button(6) 
C Button D = button(1) 
C Button L = 
C Button R = button(0)  
X Axis = axis(0-,0+)  
Y Axis = axis(1-,1+)  
L Trig = button(6)  
R Trig = button(5)  
A Button = button(2)  
B Button = button(3)  
Z Trig = button(4)  
Start = button(9)  
; Twin USB Joystick_END 

